---
$schema: "file://../.moon/cache/schemas/project.json"
id: github
language: bash
layer: tool

tasks:
  test:
    script: |
      bats tasks/*.bats
      actionlint workflows/release.yml workflows/publish.yml
    inputs:
      - "actions/**/*"
      - "tasks/**/*"
      - "workflows/**/*"
      - "/.memory/docs/adr/0009-coordinate-releases-with-release-please-and-moon.md"